### ISSUE TITLE
"kø" in text-to-lexemes extracts only "k"

### ISSUE THREAD

**Issue by fnielsen** [fnielsen/ordia#56]
"kø" in text-to-lexemes extracts only "k"

**Comment by jhsoby** [comment]
This is fixed already, isn't it? Works for me at least.

**Comment by fnielsen** [comment]
No, I still get a problem: https://ordia.toolforge.org/text-to-lexemes?text-language=da&text=k%C3%B8

**Comment by jhsoby** [comment]
Aha. Or only happens for that mode (lowercase first sentence letters), and it happens for all two-letter words, so it's not a Unicorn issue. I looked at the code, and I think the culprit is the 2 in this line: https://github.com/fnielsen/ordia/blob/90b1b91344e42bf0e44d949fddd471d131e38df3/ordia/text.py#L45

**Comment by fnielsen** [comment]
Now running https://ordia.toolforge.org/text-to-lexemes?text-language=da&text=k%C3%B8 Thanks for the PR.
